### ISSUE TITLE
Menus are down

### ISSUE THREAD

**Issue by thebradbain** [aspc/aspc-website#159]
We need to fix Frank, Frary, Oldenborg, Scripps, and Mudd menus ASAP 😬 

- [x] Frank
- [x] Frary
- [x] Oldenborg
- [x] Scripps
- [x] Mudd

**Comment by itshuey** [comment]
Doesn't seem like Mudd/Scripps is a problem on our end.
[Mudd's website](https://menus.sodexomyway.com/BiteMenu/Menu?menuId=344&locationId=13147001&whereami=http://hmc.sodexomyway.com/dining-near-me/hoch-shanahan-dining-commons), [today's query](https://menus.sodexomyway.com/BiteMenu/MenuOnly?locationId=13147001&menuId=344&startDate=2019-09-02), [two months earlier](https://menus.sodexomyway.com/BiteMenu/MenuOnly?locationId=13147001&menuId=344&startDate=2019-07-02). Similar for Scripps.

For the Pomona Dining Halls, I'm getting this error when I try to rake:
`Selenium::WebDriver::Error::SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 77`

If it is just a problem with the headless browser, it might be a simple fix.
Alternatively, it seems like the website loads with the containers for each day already open, so we don't really to simulate clicks here. Unless I'm missing something, it seems like we can grab the html and parse it directly?
