### ISSUE TITLE
Vagrant up failing on setup

### ISSUE THREAD

**Issue by itshuey** [aspc/aspc-website#162]
Running 'vagrant up' fails with the following error:

` default: NoMethodError: Cannot load Rails.application.database_configuration:  `
` default: undefined method [] for nil:NilClass `

This is because even though the production db configurations aren't being used for the test/development modes, the configurations still get parsed, so Rails will throw an error when it tries to access [:production] of null in database.yml here:

 `password: <%= Rails.application.credentials[:database_credentials][:production] %>`

The fix is documented [here](https://stackoverflow.com/questions/28698108/cannot-load-rails-application-database-configuration-undefined-method-for?rq=1).

**Comment by saatvikkher** [comment]
Bringing this back. We can probably fix this permanently.

**Comment by Eshaan-Lumba** [comment]
No longer using vagrant
