### ISSUE TITLE
FA 23 Term in Course Planner does not populate results

### ISSUE THREAD

**Issue by LukeRDavis** [aspc/aspc-website#277]
https://pomonastudents.org/courses/planner

Just in case it's a population error (as in too many items), I tried using two filters to shrink the number of expected classes and that did not populate results either. This issue was also reproduced on a computer at ITS office under a different login.

![image](https://user-images.githubusercontent.com/34807339/231302681-166c170a-6205-4c6d-8ac0-3de3b22621e4.png)

**Comment by saatvikkher** [comment]
Hey, Luke thanks for the issue. We're working on updating the planner w/ FA23 offerings.
