### ISSUE TITLE
Add senator/staff bios and headshots

### ISSUE THREAD

**Issue by srichards11** [aspc/aspc-website#75]
BIOS:
https://docs.google.com/document/d/15zryB0gHTEz3VgHrpgRDH6riTUl0252KIp-ZWWNvgNY/edit?usp=sharing

PHOTOS:
https://drive.google.com/drive/folders/1p_hu5_-NUOocRd1CY6xwE_QLDladPb2I?usp=sharing

If a person is missing a bio/photo, don't worry. Just add what is here.

**Comment by pavlerohalj** [comment]
#90
