### ISSUE TITLE
Add content to PEC page

### ISSUE THREAD

**Issue by srichards11** [aspc/aspc-website#76]
Pomona Events Committee (PEC) is a subcommittee of ASPC that uses the student fees that you pay to help sponsor events for students. Our mission is to implement social, cultural, and recreational events to meet the broad social needs of the students of Pomona College. These events range anywhere from films on the weekends, to parties in Doms, to Symposium, to various off campus events. PEC priorities include welcoming, embracing, and reflecting the inclusivity and  diversity of Pomona College and its student body! If you want to become more involved with PEC applications season is always at the end of spring semester and at some times the beginning of fall semester for the incoming class of first years!

Check out our Facebook here: https://www.facebook.com/PomonaEvents/?ref=br_rs

**Comment by pavlerohalj** [comment]
#79
